import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import '@/styles/globals.css';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

const geistSans = Geist({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Eventure',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.className}  antialiased min-h-screen bg-[#121212] text-white`}>
                <Navigation />
                {children}
                <Footer />
            </body>
        </html>
    );
}
